Merge from upstream/hanoi in order to release 1.3.1 snap
canonical/edgex-app-service-configurable pull request #7
Opened 2021-02-25 17:58 UTC by siggiskulason

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number:

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Are there any new imports or modules? If so, what are they used for and why?

## Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2021-03-01 19:46 UTC, tonyespy requested changes
One change (see inline comment) needs to be addressed...

2021-03-01 19:46 UTC, tonyespy commented on snap/README.md
> +sudo snap set edgex-app-service-configurable security-secret-store=false
Unfortunately it looks like I documented this incorrectly in the upstream PR, the value should `off`, not `false` to disable usage of the secret store. Please see the associated change to the `security-secret-store-env-var.sh`. FYI I kept off in this case even though the underlying environment variable supports `TRUE/FALSE`. 

Maybe we should modify the code to support either and do a case-less comparison?

**Note** - we need to fix this in the upstream repository as well...

2021-03-02 15:58 UTC, siggiskulason commented on snap/README.md
> +sudo snap set edgex-app-service-configurable security-secret-store=false
Thanks for raising this issue. As discussed in our standup, we should merge this PR as-is and then you were going to create a new PR with this fix.

2021-03-02 16:26 UTC, tonyespy approved these changes
Based upon discussion re: the one issue surfaced, I'm going to approve this PR, and submit a follow-up PR to address the inaccurate README.

2021-03-02 16:26 UTC, merged